# Generated by Django 4.0.7 on 2022-09-11 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accidente',
            fields=[
                ('accidenteid', models.AutoField(db_column='AccidenteID', primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(db_column='Fecha')),
                ('descripcion', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Descripcion', max_length=500)),
                ('medidas', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Medidas', max_length=500)),
            ],
            options={
                'db_table': 'Accidente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('actividadid', models.AutoField(db_column='ActividadID', primary_key=True, serialize=False)),
                ('fechacreacion', models.DateTimeField(db_column='FechaCreacion')),
                ('estadoactividad', models.SmallIntegerField(db_column='EstadoActividad')),
                ('actividadextra', models.SmallIntegerField(db_column='ActividadExtra')),
            ],
            options={
                'db_table': 'Actividad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Asesoria',
            fields=[
                ('asesoriaid', models.AutoField(db_column='AsesoriaID', primary_key=True, serialize=False)),
                ('estado', models.SmallIntegerField(blank=True, db_column='Estado', null=True)),
                ('fechaasesoria', models.DateTimeField(db_column='FechaAsesoria')),
                ('descripcionasesoria', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='DescripcionAsesoria', max_length=500)),
            ],
            options={
                'db_table': 'Asesoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Asesoriatelefonica',
            fields=[
                ('asesoriatelefonicaid', models.AutoField(db_column='AsesoriaTelefonicaID', primary_key=True, serialize=False)),
                ('dudacliente', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='DudaCliente', max_length=250)),
                ('respuestaempleado', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='RespuestaEmpleado', max_length=250)),
                ('fechahora', models.DateTimeField(db_column='FechaHora')),
            ],
            options={
                'db_table': 'AsesoriaTelefonica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Capacitacion',
            fields=[
                ('capacitacionid', models.AutoField(db_column='CapacitacionID', primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(db_column='Fecha')),
                ('cantidadasistentes', models.IntegerField(db_column='CantidadAsistentes')),
                ('materiales', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='Materiales', max_length=200, null=True)),
                ('descripcion', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='Descripcion', max_length=200, null=True)),
            ],
            options={
                'db_table': 'Capacitacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('checklistid', models.AutoField(db_column='ChecklistID', primary_key=True, serialize=False)),
                ('fechachecklist', models.DateField(db_column='FechaChecklist')),
            ],
            options={
                'db_table': 'Checklist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rutcliente', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='RutCliente', max_length=12, primary_key=True, serialize=False)),
                ('razonsocial', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='RazonSocial', max_length=50)),
                ('rubro', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Rubro', max_length=50)),
                ('direccion', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Direccion', max_length=100)),
                ('telefono', models.IntegerField(db_column='Telefono')),
                ('representante', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Representante', max_length=50)),
            ],
            options={
                'db_table': 'Cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('contratoid', models.AutoField(db_column='ContratoID', primary_key=True, serialize=False)),
                ('cantidadasesorias', models.IntegerField(db_column='CantidadAsesorias')),
                ('cantidadcapacitaciones', models.IntegerField(db_column='CantidadCapacitaciones')),
                ('fechacreacion', models.DateTimeField(db_column='FechaCreacion')),
                ('fechatermino', models.DateTimeField(db_column='FechaTermino')),
                ('fechapago', models.DateField(db_column='FechaPago')),
                ('cuotascontrato', models.IntegerField(db_column='CuotasContrato')),
                ('valorcontrato', models.IntegerField(db_column='ValorContrato')),
                ('pagado', models.BooleanField(db_column='Pagado', default=False)),
            ],
            options={
                'db_table': 'Contrato',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('rutempleado', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='RutEmpleado', max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Nombre', max_length=50)),
                ('apellido', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Apellido', max_length=50)),
                ('cargo', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Cargo', max_length=50)),
            ],
            options={
                'db_table': 'Empleado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Informevisita',
            fields=[
                ('informevisitaid', models.AutoField(db_column='InformeVisitaID', primary_key=True, serialize=False)),
                ('situacion', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Situacion', max_length=500)),
                ('fecha', models.DateField(db_column='Fecha')),
            ],
            options={
                'db_table': 'InformeVisita',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Itemschecklist',
            fields=[
                ('itemcheclistid', models.AutoField(db_column='ItemCheclistID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Nombre', max_length=50)),
                ('aprobado', models.SmallIntegerField(blank=True, db_column='Aprobado', null=True)),
                ('reprobado', models.SmallIntegerField(blank=True, db_column='Reprobado', null=True)),
                ('semiaprobado', models.SmallIntegerField(blank=True, db_column='SemiAprobado', null=True)),
            ],
            options={
                'db_table': 'ItemsChecklist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mejora',
            fields=[
                ('mejoraid', models.AutoField(db_column='MejoraID', primary_key=True, serialize=False)),
                ('planmejora', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='PlanMejora', max_length=500)),
                ('fecha', models.DateField(db_column='Fecha')),
                ('aplicomejora', models.SmallIntegerField(db_column='AplicoMejora')),
            ],
            options={
                'db_table': 'Mejora',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('pagosid', models.AutoField(db_column='PagosID', primary_key=True, serialize=False)),
                ('fechapago', models.DateTimeField(db_column='FechaPago')),
                ('fechavencimiento', models.DateTimeField(db_column='FechaVencimiento')),
                ('valorcuota', models.DecimalField(db_column='ValorCuota', decimal_places=4, max_digits=19)),
                ('montoextra', models.DecimalField(db_column='MontoExtra', decimal_places=4, max_digits=19)),
                ('valorpago', models.DecimalField(db_column='ValorPago', decimal_places=4, max_digits=19)),
            ],
            options={
                'db_table': 'Pagos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RubroEmpresa',
            fields=[
                ('rubroid', models.AutoField(db_column='RubroID', primary_key=True, serialize=False)),
                ('rubro', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Rubro', max_length=50)),
            ],
            options={
                'db_table': 'RubroEmpresa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipopagos',
            fields=[
                ('tipopagoid', models.AutoField(db_column='TipoPagoID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Nombre', max_length=50)),
            ],
            options={
                'db_table': 'TipoPagos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('visitaid', models.AutoField(db_column='VisitaID', primary_key=True, serialize=False)),
                ('fechavisita', models.DateTimeField(db_column='FechaVisita')),
                ('estado', models.SmallIntegerField(db_column='Estado')),
            ],
            options={
                'db_table': 'Visita',
                'managed': False,
            },
        ),
    ]
