# Generated by Django 4.0.7 on 2022-10-12 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historialactividad',
            fields=[
                ('historialactividadid', models.AutoField(db_column='HistorialActividadID', primary_key=True, serialize=False)),
                ('tipoactividad', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='TipoActividad', max_length=50)),
                ('fechacreacion', models.DateTimeField(db_column='FechaCreacion')),
                ('fecharealizada', models.DateTimeField(db_column='FechaRealizada')),
                ('estado', models.BooleanField(db_column='Estado')),
            ],
            options={
                'db_table': 'HistorialActividad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Valorextra',
            fields=[
                ('valorid', models.AutoField(db_column='ValorID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Nombre', max_length=50)),
                ('valor', models.DecimalField(db_column='Valor', decimal_places=4, max_digits=19)),
            ],
            options={
                'db_table': 'ValorExtra',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Actividad',
        ),
    ]
