# Generated by Django 4.0.7 on 2022-10-11 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='NombreUsuario', max_length=50, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, db_column='FechaCreacion')),
                ('last_login', models.DateTimeField(auto_now=True, db_column='Last_login')),
                ('is_staff', models.BooleanField(db_column='Is_staff', default=False)),
                ('is_active', models.BooleanField(db_column='Estado', default=True)),
                ('is_profesional', models.BooleanField(db_column='Is_Profesional', default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
