# Generated by Django 4.0.7 on 2022-11-11 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(db_column='CorreoElectronico', max_length=254, null=True),
        ),
    ]
